<a href="https://colab.research.google.com/github/zisunning/personal1/blob/main/Midterm_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
def Q1() :
  a = np.arange(1,65).reshape(8,8)
  print("Original array A \n", a)
  print("Shape of original :", a.shape)
  a=a.reshape(8,4,2)
  print("Reshaped array A \n", a)
  print("Shape of reshaped :", a.shape)



In [ ]:
def Q2() :
  c = np.arange(1,10001)
  d = c[1::2]
  print(d)

In [ ]:
from google.colab import drive

#load train data and label
drive.mount('/content/drive')
train_data_path = "/content/drive/MyDrive/2021_ML/project/train_data.npy"
train_label_path = "/content/drive/MyDrive/2021_ML/project/train_label.npy"

train_data = np.load(train_data_path, allow_pickle=True)
train_label_rawdata = np.load(train_label_path, allow_pickle=True)  

num_train_data = len(train_data)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
print(train_data.shape)

(2682,)


In [ ]:
def Q3() :
  sequence_data = np.zeros(num_train_data)
  for i in range(num_train_data):
    temp_data = len(train_data[i])
    sequence_data[i] = temp_data

  longest_game = np.argmax(sequence_data)
  print("Index of the longest : ", longest_game)
  shortest_game = np.argmin(sequence_data)
  print("Index of the shortest : ", shortest_game)

In [ ]:
def Q4() :
  k = random.randint(0,num_train_data)
  dix_list = []
  for i in range(10) :
   for y in range(19) : 
      for x in range(19) : 
        if i == 0 :
          if train_data[k][i][0][y][x] != 0 :
            dix_list.append([y,x])
        else : 
          if train_data[k][i][0][y][x] != train_data[k][i-1][0][y][x] :
            dix_list.append([y,x])

  print(dix_list)

In [ ]:
def Q5() : 
  count_list=[]
  total = 0
  for j in range(num_train_data) :
    num = 0
    for y in range(9) : 
      for x in range(9) : 
        if (train_data[j][-1][0][y][x] == 1) or (train_data[j][-1][0][y][x] == -1) :
          num+=1
    count_list.append(num)

  game_idx = np.argmax(count_list)
  small_num = count_list[game_idx]
  for y in range(19) :
     for x in range(19) :
       if (train_data[game_idx][-1][0][y][x] == 1) or (train_data[game_idx][-1][0][y][x] == -1) :
          total+=1

  print("Index of the game :", game_idx)
  print("A/B :", small_num / total)



In [ ]:
def main() :
  print("Question 1 : ")
  Q1()
  print("\n")
  print("Question 2 : ")
  Q2()
  print("\n")
  print("Question 3 : ")
  Q3()
  print("\n")
  print("Question 4 : ")
  Q4()
  print("\n")
  print("Question 5 : ")
  Q5()


if __name__ == "__main__":
    main()


Question 1 : 
Original array A 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
Shape of original : (8, 8)
Reshaped array A 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]

 [[33 34]
  [35 36]
  [37 38]
  [39 40]]

 [[41 42]
  [43 44]
  [45 46]
  [47 48]]

 [[49 50]
  [51 52]
  [53 54]
  [55 56]]

 [[57 58]
  [59 60]
  [61 62]
  [63 64]]]
Shape of reshaped : (8, 4, 2)


Question 2 : 
[    2     4     6 ...  9996  9998 10000]


Question 3 : 
Index of the longest :  2678
Index of the shortest :  2511


Question 4 : 
[[3, 3], [3, 15], [15, 2], [16, 15], [14, 16], [10, 16], [5, 16], [7, 16], [16, 12], [15, 14]]


Question 5 : 
Index of the game : 272
A/B : 0.23076923076923078
